#!/usr/bin/env bash

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions plugins/zsh-autosuggestions
curl -o plugins/git-completion.bash https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
curl -o plugins/_git https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh
