#!/usr/bin/env bash

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions plugins/zsh-autosuggestions
git clone https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/docker-composes plugins/docker-compose